name: Second-workflow-for-parallel-and-dependent-jobs
on: [push]

jobs:
    linux-job:
        runs-on: ubuntu-latest
        steps:
            - name: printing linux kernal os info
              run: uname -a
    mac-os-job:
        runs-on: mac-latest
        steps:
            - name: printing mac sw version
              run: sw -vers
    windows-job:
        runs-on: windows-latest
        needs: linux-job
        steps:
            - name: list dir file information
              run: dir

#if commit message is with [no actions],[actions no],[ci skip],[skip ci],[no ci],[ci no] it won't run work flow